### ISSUE TITLE
[BUG]: onProgress not returning decibels for Web

### ISSUE THREAD

**Issue by mpopolin** [Canardoux/flutter_sound#838]
## Flutter Sound Version : 

- FULL

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```
|-- flutter_sound 9.1.2
|   |-- flutter_sound_platform_interface 9.1.2
|   |-- flutter_sound_web 9.1.2
|   |   |-- flutter_sound_platform_interface...
----------------------------------------------------------

## Severity
- Result is not what expected

--------------------------------------------------------

## Platforms you faced the error 
- Flutter Web

------------------------------------------------

**Describe the bug**
The onProgress callback is called but the decibels value is always 0 when running on web. Also https://flutter-sound.canardoux.xyz/web_example/#/ Recorder onProgress does not shows the decibels

**To Reproduce**
1. Go to https://flutter-sound.canardoux.xyz/web_example/#/
2. Click on Recorder onProgress
3. Click on Go
4. See error - no db value showing.
-----------------------------------------------------------------

**Comment by GeorgeAmgad** [comment]
Should be fixed in 9.1.3

**Comment by mpopolin** [comment]
Even with the fix mentioned, when I do the flutter build web, the coded that is imported (saw from the imports on network tab when opening the app) still retuning the hardcoded 0 value. Still missing something?

**Comment by aleslanik2** [comment]
Hi, i think in current stable is not PR merged. When i look to my_project/build/web/assets/packages/flutter_sound_web/src/flutter_sound_recorder.js so on line 413 is that block of code
```
function () {
         var now = new Date().getTime();
         var distance = now - me.countDownDate;
         me.callbackTable[CB_updateRecorderProgress](me.callback, me.deltaTime + distance, 0);
},
```

**Comment by Larpoux** [comment]
That's right. I probably did again a mistake when I merged @GeorgeAmgad Pull Request.
I am very sorry and will fix that as soon as I will have access to my computers

**Comment by GeorgeAmgad** [comment]
Well probably this time it's my mistake, I added the files in `js` folder not in `src`, it should be working if you are importing the js files in `index.html` (which was the default step to do before `9.1.1` when I added the feature) but now they are imported by default from `src` folder which doesn't include the addition .. sorry for the mess.

@Larpoux To fix this you will just need to copy `flutter_sound_recorder.js` from `js/flutter_sound` to `src`.

**Comment by aleslanik2** [comment]
I found duplicated issue https://github.com/Canardoux/flutter_sound/issues/862

**Comment by bloemy7** [comment]
Can we get this merged in/fixed? Seems like it's still an ongoing issue.

**Comment by Larpoux** [comment]
Fixed in Flutter Sound 9.4.7. Thanks to @bloemy7
